import pandas as pd

# Leitura de arquivos
df_csv = pd.read_csv('file.csv')
df_excel = pd.read_excel('file.xlsx')
df_json = pd.read_json('file.json')
df_sql = pd.read_sql('SELECT * FROM table', con)
df_html = pd.read_html('file.html')
df_feather = pd.read_feather('file.feather')
df_parquet = pd.read_parquet('file.parquet')
df_clipboard = pd.read_clipboard()
df_pickle = pd.read_pickle('file.pkl')

# Escrita de arquivos
df.to_csv('file.csv')
df.to_excel('file.xlsx')
df.to_json('file.json')
df.to_sql('table', con)
df.to_html('file.html')
df.to_feather('file.feather')
df.to_parquet('file.parquet')
df.to_clipboard()
df.to_pickle('file.pkl')

# Criação de objetos
df = pd.DataFrame(data)
s = pd.Series(data)
idx = pd.Index(data)
cat = pd.Categorical(data)
timestamp = pd.Timestamp('2025-01-01')
timedelta = pd.Timedelta(days=1)
date_range = pd.date_range(start='2025-01-01', periods=5)
period_range = pd.period_range(start='2025-01-01', periods=5, freq='D')
timedelta_range = pd.timedelta_range(start='0 days', periods=5, freq='D')

# Manipulação de dados
df_concat = pd.concat([df1, df2])
df_merge = pd.merge(df1, df2, on='key')
df_melt = pd.melt(df, id_vars=['A'])
df_pivot = pd.pivot(df, index='A', columns='B', values='C')
df_pivot_table = pd.pivot_table(df, values='C', index='A', columns='B')
df_crosstab = pd.crosstab(df['A'], df['B'])
df_dummies = pd.get_dummies(df['A'])
df_cut = pd.cut(df['A'], bins=3)
df_qcut = pd.qcut(df['A'], q=3)

# Outros utilitários
unique_vals = pd.unique(df['A'])
factorized_vals = pd.factorize(df['A'])
na_vals = pd.notna(df['A'])
na_vals = pd.isna(df['A'])
eval_result = pd.eval('df['A'] + df['B']')
with pd.option_context('display.max_rows', 10):
    print(df)
pd.set_option('display.max_rows', 10)
pd.reset_option('display.max_rows')
df.index
df.columns
df.dtypes
df.shape
df.size
df.values
df_loc = df.loc[0]
df_iloc = df.iloc[0]
df_at = df.at[0, 'A']
df_iat = df.iat[0, 0]
df_filtered = df.filter(items=['A'])
df_sample = df.sample(n=3)
df_assign = df.assign(C=df['A'] + df['B'])
df_drop = df.drop(columns=['A'])
df_rename = df.rename(columns={'A': 'Alpha'})
df_set_index = df.set_index('A')
df_reset_index = df.reset_index()
df_sort_values = df.sort_values(by='A')
df_sort_index = df.sort_index()
df_replace = df.replace({'A': {1: 100}})
df_fillna = df.fillna(0)
df_dropna = df.dropna()
df_ffill = df.ffill()
df_bfill = df.bfill()
df_interpolate = df.interpolate()
df_count = df.count()
df_sum = df.sum()
df_mean = df.mean()
df_median = df.median()
df_std = df.std()
df_var = df.var()
df_min = df.min()
df_max = df.max()
df_idxmin = df.idxmin()
df_idxmax = df.idxmax()
df_describe = df.describe()
df_corr = df.corr()
df_cov = df.cov()
df_value_counts = df['A'].value_counts()
df_mode = df.mode()
df_quantile = df.quantile(0.5)
df_apply = df.apply(lambda x: x.max())
df_applymap = df.applymap(lambda x: x * 2)
df_map = df['A'].map(lambda x: x + 1)
df_pipe = df.pipe(lambda df: df + 1)
df_groupby = df.groupby('A').sum()
df_aggregate = df.aggregate({'A': 'sum', 'B': 'mean'})
df_agg = df.agg({'A': 'sum', 'B': 'mean'})
df_transform = df.transform(lambda x: x + 1)
df_expanding = df.expanding().sum()
df_rolling = df.rolling(2).sum()
df_resample = df.resample('D').sum()
df_append = df.append(df2)
df_merge = df.merge(df2, on='A')
df_join = df.join(df2, on='A')
df_concat = pd.concat([df1, df2])
df_str_contains = df['A'].str.contains('abc')
df_str_startswith = df['A'].str.startswith('A')
df_str_endswith = df['A'].str.endswith('B')
df_str_replace = df['A'].str.replace('A', 'X')
df_str_extract = df['A'].str.extract(r'(\d+)')
df_str_split = df['A'].str.split(',')
df_str_upper = df['A'].str.upper()
df_str_lower = df['A'].str.lower()
df_str_strip = df['A'].str.strip()
df_head = df.head(5)
df_tail = df.tail(5)
df_info = df.info()
df_memory_usage = df.memory_usage()
df_style = df.style
df_plot = df.plot(kind='line', x='A', y='B')
s.index
s.dtype
s.shape
s.size
s.values
s.name
s_dropna = s.dropna()
s_fillna = s.fillna(0)
s_replace = s.replace(1, 100)
s_sort_values = s.sort_values()
s_sort_index = s.sort_index()
s_rename = s.rename('New Name')
s_reset_index = s.reset_index()
s_set_index = s.set_index('A')
s_count = s.count()
s_sum = s.sum()
s_mean = s.mean()
s_median = s.median()
s_std = s.std()
s_var = s.var()
s_min = s.min()
s_max = s.max()
s_idxmin = s.idxmin()
s_idxmax = s.idxmax()
s_describe = s.describe()
s_value_counts = s.value_counts()
s_mode = s.mode()
s_quantile = s.quantile(0.5)
s_apply = s.apply(lambda x: x + 1)
s_map = s.map(lambda x: x * 2)
s_pipe = s.pipe(lambda s: s + 1)
s_str_contains = s.str.contains('abc')
s_str_startswith = s.str.startswith('A')
s_str_endswith = s.str.endswith('B')
s_str_replace = s.str.replace('A', 'X')
s_str_extract = s.str.extract(r'(\d+)')
s_str_split = s.str.split(',')
s_str_upper = s.str.upper()
s_str_lower = s.str.lower()
s_str_strip = s.str.strip()
idx.astype('int64')
idx_rename = idx.rename('New Name')
idx_set_names = idx.set_names(['Level 1'])
idx_append = idx.append(pd.Index([4, 5]))
idx_drop = idx.drop(1)
idx_insert = idx.insert(0, 0)
idx_delete = idx.delete(0)
idx_is_monotonic = idx.is_monotonic
idx_is_unique = idx.is_unique
idx_duplicated = idx.duplicated()
idx_get_loc = idx.get_loc(3)
idx_get_indexer = idx.get_indexer([1, 2])
idx_to_list = idx.to_list()
